parameters:
    database_host: localhost
    database_port: 3306
    database_name: hackgames
    database_user: malik
    database_password: newuser1
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
