<?php

namespace wcs\hackathonBundle\Repository;

/**
 * highscoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class highscoreRepository extends \Doctrine\ORM\EntityRepository
{
}
