<?php

namespace wcs\hackathonBundle\Repository;

/**
 * questionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionsRepository extends \Doctrine\ORM\EntityRepository
{
}
